### ISSUE TITLE
How barcode files are generated?

### ISSUE THREAD

**Issue by mathavanpu** [labroo2/rtassel_supp#2]
Hello,
I am running the TASSEL pipeline, GBSSeqToTagDBPlugin step I got this output.
I have a query, how does this script generate  116 characters barcode. Generally, the barcode size is much smaller than what I have got here. Please enlighten my knowledge

Command Used
run_pipeline.pl -Xms514g -Xmx754g -fork1 -GBSSeqToTagDBPlugin -e MseI -i . -db GBS_BM_MseI.db -k fakebarcodes_key.tsv -c 3 -kmerLength 64 -minKmerL 20 -mnQS 20 -mxKmerNum 100000000 -endPlugin -runfork1

FullSampleName  DNASample       Flowcell        Lane    Barcode Enzyme
S10_MB_1.clean.fq       C8B56ANXX1_3_fastq.fastq        C8B56ANXX1      3    **CCCATAGATGGCGTAGCCAATAAGGTGTATGTCTTGGACCACGATATACTTTTTAATATATTAACGTACCACGAGGGACTTCATGACATATTGGTGGAGTAGACCCAAATCAATGT**    MseI

**Comment by labroo2** [comment]
Dear Mathavan,

The function makes the barcodes with the following statement:

fake_barcodes[i] <- paste(sample(c("A", "T" ,"C" ,"G"), size = read_length -
sequence_lengths[i],
replace = TRUE), collapse = "")

Basically, it takes the read length you specify or leave as default with
the initial call to the function here: barcode_faker(fastq_dir =
"C:/Users/yourname/yourfastqs", read_length = 100)

Then, it takes the sequence length of the first read of the file. The
difference between your read length and the first read sequence length is
the length of the barcode (here, 118 characters as you mentioned). To form
the barcode sequence, the function randomly samples nucleotides (ATCG).

The user does not set the length of the barcode sequence themselves. It is
OK that the barcode length is unrealistic, because TASSEL will just cut off
the barcode sequence from your read anyway :) The barcode sequence only
serves to identify the samples. I hope this is helpful.

Best regards,
Marlee
